import Forms.*;

public class CalculatorFiguras extends javax.swing.JFrame {
    
    /**
     * Creates new form Figuras
     */
    public CalculatorFiguras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mnbMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        mnbCuadrado = new javax.swing.JMenuItem();
        mnbRectangulo = new javax.swing.JMenuItem();
        mnbTriangulo = new javax.swing.JMenuItem();
        mnbCirculo = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnbHexaedro = new javax.swing.JMenuItem();
        mnbPoliedro = new javax.swing.JMenuItem();
        mbnTetraedro = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        btnClose = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Figuras");

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setText("<html>"
            + "<p> Autor Jose Maria Garcia Mendoza"
            + "<p> Grado 4 Grupo B"
            + "<p> Calculadora de Propiedades de las Figuras"
            + "</html>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        desktop.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopLayout.createSequentialGroup()
                .addGap(0, 1067, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopLayout.createSequentialGroup()
                .addGap(0, 679, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("Figuras ");
        jMenu1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jMenu3.setText("Figuras I");
        jMenu3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        mnbCuadrado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnbCuadrado.setText("Cuadrado");
        mnbCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnbCuadradoActionPerformed(evt);
            }
        });
        jMenu3.add(mnbCuadrado);

        mnbRectangulo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnbRectangulo.setText("Rectangulo");
        mnbRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnbRectanguloActionPerformed(evt);
            }
        });
        jMenu3.add(mnbRectangulo);

        mnbTriangulo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnbTriangulo.setText("Triangulo");
        mnbTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnbTrianguloActionPerformed(evt);
            }
        });
        jMenu3.add(mnbTriangulo);

        mnbCirculo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnbCirculo.setText("Circulo");
        mnbCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnbCirculoActionPerformed(evt);
            }
        });
        jMenu3.add(mnbCirculo);

        jMenu1.add(jMenu3);

        jMenu4.setText("Figuras II");
        jMenu4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        mnbHexaedro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnbHexaedro.setText("Hexaedro");
        mnbHexaedro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnbHexaedroActionPerformed(evt);
            }
        });
        jMenu4.add(mnbHexaedro);

        mnbPoliedro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnbPoliedro.setText("Poliedro");
        mnbPoliedro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnbPoliedroActionPerformed(evt);
            }
        });
        jMenu4.add(mnbPoliedro);

        mbnTetraedro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mbnTetraedro.setText("Tetraedro");
        mbnTetraedro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbnTetraedroActionPerformed(evt);
            }
        });
        jMenu4.add(mbnTetraedro);

        jMenu1.add(jMenu4);
        jMenu1.add(jSeparator1);

        btnClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        btnClose.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnClose.setText("Cerrar");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jMenu1.add(btnClose);

        mnbMenu.add(jMenu1);

        setJMenuBar(mnbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnbCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnbCuadradoActionPerformed
        frmCuadrado frmC = new frmCuadrado();
        this.desktop.add(frmC);
        frmC.show();
    }//GEN-LAST:event_mnbCuadradoActionPerformed

    private void mnbRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnbRectanguloActionPerformed
        frmRectangulo frmR = new frmRectangulo();
        this.desktop.add(frmR);
        frmR.show();
    }//GEN-LAST:event_mnbRectanguloActionPerformed

    private void mnbTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnbTrianguloActionPerformed
        frmTriangulo frmT = new frmTriangulo();
        this.desktop.add(frmT);
        frmT.show();
    }//GEN-LAST:event_mnbTrianguloActionPerformed

    private void mnbCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnbCirculoActionPerformed
        frmCirculo frmC = new frmCirculo();
        this.desktop.add(frmC);
        frmC.show();
    }//GEN-LAST:event_mnbCirculoActionPerformed

    private void mnbHexaedroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnbHexaedroActionPerformed
        frmCubo frmCu = new frmCubo();
        this.desktop.add(frmCu);
        frmCu.show();
    }//GEN-LAST:event_mnbHexaedroActionPerformed

    private void mnbPoliedroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnbPoliedroActionPerformed
        frmPrismaRectangular frmPR = new frmPrismaRectangular();
        this.desktop.add(frmPR);
        frmPR.show();
    }//GEN-LAST:event_mnbPoliedroActionPerformed

    private void mbnTetraedroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbnTetraedroActionPerformed
        frmTetraedro frmTe = new frmTetraedro();
        this.desktop.add(frmTe);
        frmTe.show();
    }//GEN-LAST:event_mbnTetraedroActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CalculatorFiguras window = new CalculatorFiguras();
                window.setExtendedState(MAXIMIZED_BOTH);
                window.setLocationRelativeTo(null);
                window.setVisible(true );
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnClose;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mbnTetraedro;
    private javax.swing.JMenuItem mnbCirculo;
    private javax.swing.JMenuItem mnbCuadrado;
    private javax.swing.JMenuItem mnbHexaedro;
    private javax.swing.JMenuBar mnbMenu;
    private javax.swing.JMenuItem mnbPoliedro;
    private javax.swing.JMenuItem mnbRectangulo;
    private javax.swing.JMenuItem mnbTriangulo;
    // End of variables declaration//GEN-END:variables
}
