package Forms;
import Dependences.Circulo;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author josem
 */
public class frmCirculo extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmCirculo
     */
    public frmCirculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtRadio = new javax.swing.JTextField();
        btnArea = new javax.swing.JButton();
        btnCircuferencia = new javax.swing.JButton();
        btnDiametro = new javax.swing.JButton();
        btnArco = new javax.swing.JButton();
        btnSemiperimetro = new javax.swing.JButton();

        setClosable(true);
        setTitle("Circulo");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Circle.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Radio:");

        btnArea.setText("Area");
        btnArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaActionPerformed(evt);
            }
        });

        btnCircuferencia.setText("Circuferencia");
        btnCircuferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCircuferenciaActionPerformed(evt);
            }
        });

        btnDiametro.setText("Diametro");
        btnDiametro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiametroActionPerformed(evt);
            }
        });

        btnArco.setText("Arco");
        btnArco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArcoActionPerformed(evt);
            }
        });

        btnSemiperimetro.setText("Semiperimetro");
        btnSemiperimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSemiperimetroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCircuferencia, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(btnArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDiametro, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(btnArco, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(btnSemiperimetro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnArea)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCircuferencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDiametro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnArco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSemiperimetro)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaActionPerformed
        try {
            double radio = Double.parseDouble(this.txtRadio.getText());
            Circulo A = new Circulo(radio);
            Circulo B = new Circulo();
            B = B.calculateArea(A);
            MessageBox.show(this, "El area del circulo es " + B.getArea() + " cm^2", 
                    "Area del circulo");
        } catch (Exception e) {
            MessageBox.show(this, e.getMessage(), "Exception");
        }
    }//GEN-LAST:event_btnAreaActionPerformed

    private void btnCircuferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCircuferenciaActionPerformed
        try {
            double radio = Double.parseDouble(this.txtRadio.getText());
            Circulo A = new Circulo(radio);
            Circulo B = new Circulo();
            B = B.calculateCircuferencia(A);
            MessageBox.show(this, "La circuferencia del circulo es " + B.getCircuferencia()+ " cm", 
                    "Circuferencia del circulo");
        } catch (Exception e) {
            MessageBox.show(this, e.getMessage(), "Exception");
        }
    }//GEN-LAST:event_btnCircuferenciaActionPerformed

    private void btnDiametroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiametroActionPerformed
        try {
            double radio = Double.parseDouble(this.txtRadio.getText());
            Circulo A = new Circulo(radio);
            Circulo B = new Circulo();
            B = B.calculateDiametro(A);
            MessageBox.show(this, "El Diametro del circulo es " + B.getDiametro()+ " cm", 
                    "Diametro del circulo");
        } catch (Exception e) {
            MessageBox.show(this, e.getMessage(), "Exception");
        }
    }//GEN-LAST:event_btnDiametroActionPerformed

    private void btnArcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArcoActionPerformed
        try {
            double radio = Double.parseDouble(this.txtRadio.getText());
            Circulo A = new Circulo(radio, 360);
            Circulo B = new Circulo();
            B = B.calculateArco(A);
            MessageBox.show(this, "El Arco del circulo es " + B.getArco()+ " cm", 
                    "Arco del circulo");
        } catch (Exception e) {
            MessageBox.show(this, e.getMessage(), "Exception");
        }
    }//GEN-LAST:event_btnArcoActionPerformed

    private void btnSemiperimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSemiperimetroActionPerformed
        try {
            double radio = Double.parseDouble(this.txtRadio.getText());
            Circulo A = new Circulo(radio);
            Circulo B = new Circulo();
            B = B.calculateSemiperimetro(A);
            MessageBox.show(this, "El Semiperimetro del circulo es " + B.getSemiperimetro()+ " cm", 
                    "Semiperimetro del circulo");
        } catch (Exception e) {
            MessageBox.show(this, e.getMessage(), "Exception");
        }
    }//GEN-LAST:event_btnSemiperimetroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArco;
    private javax.swing.JButton btnArea;
    private javax.swing.JButton btnCircuferencia;
    private javax.swing.JButton btnDiametro;
    private javax.swing.JButton btnSemiperimetro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtRadio;
    // End of variables declaration//GEN-END:variables
}
