/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Forms;

import Dependences.Cuadrado;
import Dependences.Hexaedro;

/**
 *
 * @author josem
 */
public class frmCubo extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmCubo
     */
    public frmCubo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtLado = new javax.swing.JTextField();
        btnVolumen = new javax.swing.JButton();
        btnDiagonal = new javax.swing.JButton();
        btnAreaSuperficie = new javax.swing.JButton();
        btnAreaBase = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cubo");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Cube.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Lado:");

        btnVolumen.setText("Volumen");
        btnVolumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolumenActionPerformed(evt);
            }
        });

        btnDiagonal.setText("Diagonal");
        btnDiagonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiagonalActionPerformed(evt);
            }
        });

        btnAreaSuperficie.setText("AreaSuperficie");
        btnAreaSuperficie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaSuperficieActionPerformed(evt);
            }
        });

        btnAreaBase.setText("Area Base");
        btnAreaBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaBaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLado, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnVolumen, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnAreaBase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAreaSuperficie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnDiagonal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnVolumen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDiagonal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAreaSuperficie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAreaBase)
                        .addContainerGap(449, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolumenActionPerformed
        try {
            Cuadrado A = new Cuadrado(Double.parseDouble(this.txtLado.getText()));
            Hexaedro B = new Hexaedro();
            B = B.calculateVolumen(B, A);
            MessageBox.show(this, "El volumen del cubo es de " + B.getVolumen() + " cm^3", "Volumen del cubo");
        } catch(NumberFormatException e){
            MessageBox.show(this, e.getMessage(), "Exception");
        } catch(Exception e){
            MessageBox.show(this, e.getMessage(), "Exception");
        }
    }//GEN-LAST:event_btnVolumenActionPerformed

    private void btnDiagonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagonalActionPerformed
        try {
            Cuadrado A = new Cuadrado(Double.parseDouble(this.txtLado.getText()));
            Hexaedro B = new Hexaedro();
            B = B.calculateDiagonal(B, A);
            MessageBox.show(this, "La longitud de la diagonal de un cubo es de " + B.getDiagonal()+ " cm", "Diagonal del cubo");
        } catch(NumberFormatException e){
            MessageBox.show(this, e.getMessage(), "Exception");
        } catch(Exception e){
            MessageBox.show(this, e.getMessage(), "Exception");
        }
    }//GEN-LAST:event_btnDiagonalActionPerformed

    private void btnAreaSuperficieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaSuperficieActionPerformed
        try {
            Cuadrado A = new Cuadrado(Double.parseDouble(this.txtLado.getText()));
            Hexaedro B = new Hexaedro();
            B = B.calculateAreaSuperficie(B, A);
            MessageBox.show(this, "El area de la superficie de un cubo es de " + B.getAreaSuperficie() + " cm^2", "Area de la superficie del cubo");
        } catch(NumberFormatException e){
            MessageBox.show(this, e.getMessage(), "Exception");
        } catch(Exception e){
            MessageBox.show(this, e.getMessage(), "Exception");
        }
    }//GEN-LAST:event_btnAreaSuperficieActionPerformed

    private void btnAreaBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaBaseActionPerformed
        try {
            Cuadrado A = new Cuadrado(Double.parseDouble(this.txtLado.getText()));
            Hexaedro B = new Hexaedro();
            B = B.calculateAreaBase(B, A);
            MessageBox.show(this, "El area de la base del cubo es de " + B.getArea() + " cm^2", "Area de la base del cubo");
        } catch(NumberFormatException e){
            MessageBox.show(this, e.getMessage(), "Exception");
        } catch(Exception e){
            MessageBox.show(this, e.getMessage(), "Exception");
        }
    }//GEN-LAST:event_btnAreaBaseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAreaBase;
    private javax.swing.JButton btnAreaSuperficie;
    private javax.swing.JButton btnDiagonal;
    private javax.swing.JButton btnVolumen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtLado;
    // End of variables declaration//GEN-END:variables
}
